[package]
cairo_version = "2.12.2"
edition = "2024_07"
name = "stark_vrf"
version = "0.1.1"
authors = ["gswirski <sognat@gmail.com>", "Cartridge"]
license = "MIT"
description = "A cairo implementation of the VRF spec (https://datatracker.ietf.org/doc/html/rfc9381) using Stark curve and Poseidon hash for efficient verification on Starknet."
homepage = "https://github.com/dojoengine/stark-vrf"
repository = "https://github.com/dojoengine/stark-vrf"
documentation = "https://github.com/dojoengine/stark-vrf"
readme = "README.md"
keywords = ["starknet", "vrf", "stark-vrf"]

[dependencies]

[dev-dependencies]
cairo_test = "2.12.2"
